### ISSUE TITLE
Need to track most recent tweet analyzed in a file

### ISSUE THREAD

**Issue by jtara1** [jtara1/GameMediaBot#1]
```
(venv) j@j-pc ~/_Github-Projects/GameMediaBot $ python3 run.py 
Retweeting: Earn 3 Fantasy Point Boosters for comple ...
Retweeting: Complete a First Win of the Day and earn ...
Retweeting: Earn 3 Fantasy Point Boosters for comple ...
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    awaiter.await()  # blocks, waiting for new tweet, classifies/predicts it, retweets if it's in trigger_targets
  File "/home/j/_Github-Projects/GameMediaBot/src/utility/await_new_tweet.py", line 30, in await
    loop.run_until_complete(wait_for_new_tweet())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/j/_Github-Projects/GameMediaBot/src/utility/await_new_tweet.py", line 26, in wait_for_new_tweet
    self._process_new_tweets(statuses)
  File "/home/j/_Github-Projects/GameMediaBot/src/utility/await_new_tweet.py", line 37, in _process_new_tweets
    self.api.PostRetweet(s.id)  # retweet this tweet
  File "/usr/local/lib/python3.5/dist-packages/twitter/api.py", line 1620, in PostRetweet
    data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
  File "/usr/local/lib/python3.5/dist-packages/twitter/api.py", line 4894, in _ParseAndCheckTwitter    
    self._CheckForTwitterError(data)                                                                   
  File "/usr/local/lib/python3.5/dist-packages/twitter/api.py", line 4914, in _CheckForTwitterError    
    raise TwitterError(data['errors'])                                                                 
twitter.error.TwitterError: [{'code': 327, 'message': 'You have already retweeted this tweet.'}]  
```

**Comment by jtara1** [comment]
closing w/ d2339f9396ec290f8cbd6cf68f1a04a18a7f28c4
